### ISSUE TITLE
MakaGiga - Error when adding feed

### ISSUE THREAD

**Issue by UnluckyLuke** [kdt/makagiga#2] opened 2017-11-04 00:56 UTC
MakaGiga doesn't seem to support Reddit feeds. Example: https://www.reddit.com/r/GameDeals/.rss

Here's the error msg:
![snulr6a 1](https://user-images.githubusercontent.com/24820252/32400654-42dd0c44-c103-11e7-8555-54ed9db76de9.png)

I believe this might be the reason:
https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/

I know this application haven't been updated for a long time but would it somehow be possible to fix this issue? Maybe it's just a small change? :)

**Comment by kdt** [comment] 2017-11-06 21:55
Hi,

> I believe this might be the reason:
https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/

No, the problem is different. After switch from RSS 2.0 to Atom it should work like before.

The error 429 (Too Many Requests) is probaly caused by too sensitive reddit server or something.

> I know this application haven't been updated for a long time

I'm working on v6.0, but it all took more time than I expected ;)

> but would it somehow be possible to fix this issue? Maybe it's just a small change? :)

It seems that setting a fake "user-agent" fixes the connection problems. It's a small change, but it need more tests. It will be probably fixed in v5.8.3.

Workaround: If you click the "Preview" button multiple times it will eventually connect w/o error...

Thanks

**Comment by kdt** [comment] 2017-12-01 19:12
OK, fixed in 5.8.3 and 5.99 Beta.
Commit: https://sourceforge.net/p/makagiga/code/10896/

**Closed as completed by kdt** 2017-12-01 19:12 UTC
Labels: bug
